//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Repository.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Balance
    {
        public int Id { get; set; }
        public int AccountId { get; set; }
        public decimal Current { get; set; }
        public Nullable<System.DateTime> LastAsOf { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
