//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Repository.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactDetail
    {
        public int Id { get; set; }
        public int AccountId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<short> Salaried { get; set; }
        public Nullable<short> Salary { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
